### ISSUE TITLE
mobie3 spec: nested grid

### ISSUE THREAD

**Issue by tischi** [mobie/covid-if-project#10]
The images in the plate in the end have names like this: 

`nuclei_WellE06_0008_E06_nuclei_plate_nuclei`

However in the `sites` `RegionDisplay` you refer to them like this:

`nuclei_WellE06_0003_E06_nuclei`

This is missing `_plate_nuclei`, which encodes the second translation (gridification) of those images.

**Comment by constantinpape** [comment]
Done.
