### ISSUE TITLE
mobie3 spec: metadataImage MUST have the same data type

### ISSUE THREAD

**Issue by tischi** [mobie/covid-if-project#11]
@constantinpape 

Maaaan, this took me hours to figure out ;-)

Mainly, because such type casting errors are often swallowed and I did not even see it...

Anyway (an example):

```
          "mergedGrid": {
            "centerAtOrigin": false,
            "mergedGridSourceName": "plate_nucleus_segmentation",
            "metadataSource": "E06_nuclei",
            "positions": [
              [
                4,
                5
              ],
              [
                4,
                6
              ]
            ],
            "sources": [
              "E06_nucleus_segmentation",
              "E07_nucleus_segmentation"
            ]
          }
```

The issue is that the metadata source`E06_nuclei` is an normal `image` of, here of `FloatType`, while the sources, e.g. `E06_nucleus_segmentation`, are `segmentation` images which have a different data type.

Thus, while it makes sense to use `E06_nuclei` here to load a minimal amount of images, it does not work, because the code also needs to fetch the data type from the metadata image.

I guess we should put this into the spec that a metadata source MUST have the same data type as the sources.

For your reference here is the code of which information I fetch from the metadata image.
All of those properties MUST be the same as for the images.

```
		this.type = metadataSource.getType().createVariable();
		this.volatileType = ( V ) MoBIEVolatileTypeMatcher.getVolatileTypeForType( type );
		this.numMipmapLevels = metadataSource.getNumMipmapLevels();
		this.numDimensions = metadataSource.getVoxelDimensions().numDimensions();
		this.voxelDimensions = metadataSource.getVoxelDimensions();
		this.levelToSourceTransform = new HashMap<>();
		this.levelToSourceDimensions = new HashMap<>();

		for ( int level = 0; level < numMipmapLevels; level++ )
		{
			final AffineTransform3D affineTransform3D = new AffineTransform3D();
			metadataSource.getSourceTransform( 0, level, affineTransform3D );
			final AffineTransform3D copy = affineTransform3D.copy();
			final long[] dimensions = metadataSource.getSource( 0, level ).dimensionsAsLongArray();
			if ( level == 0 )
			{
				System.out.println( "StitchedImage: " + name );
				System.out.println( "MetadataImage: " + metadataSource.getName() );
				System.out.println( "MetadataImage transform: " + copy );
				System.out.println( "MetadataImage dimensions: " + Arrays.toString( dimensions ) );
			}
			levelToSourceTransform.put( level, copy );
			levelToSourceDimensions.put( level, dimensions );
		}
```

**Comment by constantinpape** [comment]
This makes sense, but is there actually a view in the current project where this issue occurs? Because I don't think it should happen right now with the way I write the metadata source info right now.

**Comment by tischi** [comment]
Yes, the `default` view in the `mobie3` branch has that issue, that's where I copied it from.

**Comment by constantinpape** [comment]
> Yes, the `default` view in the `mobie3` branch has that issue, that's where I copied it from.

Ok, I fixed it. Not sure how this happened, I don't think it's the case for any of the other views.

**Comment by tischi** [comment]
Works 🥳 ....quite a big step as the mobie3 code is very different for loading this, glad that it actually works 😅. I think I'll stop for today. Thanks for the help!

<img width="441" alt="image" src="https://user-images.githubusercontent.com/2157566/193472116-0bd51e17-3e98-4b91-b050-9e539a645831.png">

**Comment by constantinpape** [comment]
I made a note of this in the spec. Will close it for now since the issue in the project is fixed.
