### ISSUE TITLE
Debug full-grid view

### ISSUE THREAD

**Issue by constantinpape** [mobie/covid-if-project#14]
We just checked with @tischi and the full grid view loads very fast now, but then it hangs. Should be further debugged at some point. @tischi: let me know if you need any extra views for this. For now I removed a lot of the debugging views we had because they were broken and it will be easier to recreate them rather than fixing them now.

**Comment by tischi** [comment]
Why are there so many objects???

<img width="924" alt="image" src="https://user-images.githubusercontent.com/2157566/198557142-7911efbf-6d1a-4bd3-849f-aae5ebb4ee17.png">


Probably an issue with the lambda?

**Comment by tischi** [comment]
It is using a lot of memory and the GC has to do a lot of stuff....

<img width="943" alt="image" src="https://user-images.githubusercontent.com/2157566/198557311-3734e962-585a-4abb-a7ef-9242648a5773.png">

**Comment by tischi** [comment]
I fixed it 🥳 
It is super smooth now, even with my horrible internet at home.
Amazing.

**Comment by tischi** [comment]
Will be fixed in `3.0.1`

**Comment by constantinpape** [comment]
Awesome! Ping me when it's uploaded :)
