### ISSUE TITLE
Views for testing

### ISSUE THREAD

**Issue by tischi** [mobie/covid-if-project#2]
@constantinpape 

Those are the current views:
```
default
default_transform_grid_with_tables_with_segmentations
default_transform_grid_with_tables_with_segmentations_without_segmentation_tables
default_with_tables_with_segmentations_without_segmentation_tables
full_grid
full_transform_grid_with_tables_with_segmentations_without_segmentation_tables
full_with_tables_with_segmentations_without_segmentation_tables
merge-grid-no-tables
single_image
trafo-grid-no-tables
```

- [ ] I think for fast debugging having the `default` as a (`two-wells-no-tables`) version would be handy.

**Comment by tischi** [comment]
- [ ] I am testing `merge-grid-no-tables` right now and it is loading tables.... maybe wrong in the view?
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/2157566/163408354-0f8d6f84-5465-47ab-9b7e-55f721af6e70.png">

**Comment by constantinpape** [comment]
>  I think for fast debugging having the `default` as a (`two-wells-no-tables`) version would be handy.

Good idea. I have put it on my after Easter TODO list.

> I am testing `merge-grid-no-tables` right now and it is loading tables.... maybe wrong in the view?

Yes, could be. I will also check after Easter.

**Comment by tischi** [comment]
@constantinpape 

Does this work for you?

`default_transform_grid_with_tables_with_segmentations_without_segmentation_tables`

While doing some other debugging I found that it appeared not to transform the images. If it also does not work for you than there either is something wrong with the view or with the transformed grid java code.

**Comment by constantinpape** [comment]
Yes, something is wrong with this view for me too:
![image](https://user-images.githubusercontent.com/4263537/164887052-939705f5-87df-4be5-8fe0-4405791df8c4.png)

I can check later if something in the json looks wrong. Could you also let me know if you still need a any other views in this project for debugging?

**Comment by tischi** [comment]
@constantinpape 

There is a bug, probably in my code. Somehow I transform the sources twice and the second transformation exactly compensates the first. 

For easier debugging, could you please add another view with this but only for the nuclei?

`default_transform_grid_with_tables_with_segmentations_without_segmentation_tables` => `default_transform_grid_only_nuclei`

**Comment by tischi** [comment]
@constantinpape 

I found it! 
For the TransformedGrid it is very important to:
`centerAtOrigin = false` in the JSON.

**Comment by constantinpape** [comment]
Hmm, I updated the view now so that `centerAtOrigin=false` for all transformed grids, but the view still looks wrong when I open it. Are you sure that this is the issue?

**Comment by constantinpape** [comment]
After reading your comment here: https://github.com/mobie/mobie-viewer-fiji/issues/679#issuecomment-1107794905
I realized that I probably switched on `centerAtOrigin=true` in too many trafos.
Do I understand it correctly that we need
- `true` for the grids that places the individual sources on the wells
- `false` for the grid that places the wells on the plate

I can update it if that's correct.

**Comment by tischi** [comment]
> * `false` for the grid that places the wells on the plate

Exactly, see also my comment in the other issue (it is not 100% logical, but this is what one has to do right now...I can explain you during a zoom).

**Comment by constantinpape** [comment]
@tischi 
I have updated `centerAtOrigin` in the bookmarks now as we have discussed and I have also checked a few of them and they all worked.
For the IgG channel I have set the contrast limit to 6500, that looks best for the full grid.

**Comment by constantinpape** [comment]
I have set `centerAtOrigin=false` for all mergedGrids now. Now all the views seem to work as expected.

**Comment by tischi** [comment]
@constantinpape 
Do we have a view with 2 wells and no segmentation at all?
Would be important for me for testing.

**Comment by constantinpape** [comment]
Hey @tischi,
I think so, but I am going on vacation for 3 weeks now and I don't have time to check this beforehand; you will need to check which one is closest to what you need for yourself. (And if none quite fit just copy the view from the json and remove the part that's referencing the segmentation).

**Comment by tischi** [comment]
I made a branch called `test-views` where I manually added some more views.

**Comment by tischi** [comment]
@constantinpape It would be great to have a `single_well_with_nuclei_segmentation` view for testing in the `mobie3` branch.

(side question: did you ever interact with the cell table for the whole plate? Is that functional or is the table too big?)

**Comment by constantinpape** [comment]
> @constantinpape It would be great to have a `single_well_with_nuclei_segmentation` view for testing in the `mobie3` branch.

Done. Though it's called `single_well_with_nucleus_segmentation`.

> (side question: did you ever interact with the cell table for the whole plate? Is that functional or is the table too big?)

Yes, we even used it for one of the figures in an early version of the paper (which was dropped for space reasons though).

**Comment by tischi** [comment]
`single_well_with_nucleus_segmentation`

<img width="564" alt="image" src="https://user-images.githubusercontent.com/2157566/193471140-efab7e1d-75c4-4d84-8699-ce7423bc7f7d.png">

I can't see the nucleus segmentation...are you sure you added it?

**Comment by constantinpape** [comment]
The source display was missing, please try again.

**Comment by tischi** [comment]
I think you may have forgotten to grid-transform the segmentation images in `single_well_with_nucleus_segmentation`.

**Comment by constantinpape** [comment]
> I think you may have forgotten to grid-transform the segmentation images in `single_well_with_nucleus_segmentation`.

No, but I referred to the wrong sources in the segmentationDisplay. Should be fixed now.
